<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="35060" started-at="2014-03-05T03:47:09Z" finished-at="2014-03-05T03:47:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="35060" started-at="2014-03-05T03:47:09Z" finished-at="2014-03-05T03:47:44Z">
      <class name="homework1.SmokeTest2">
        <test-method status="PASS" signature="start()[pri:0, instance:homework1.SmokeTest2@287cbe54]" name="start" is-config="true" duration-ms="18146" started-at="2014-03-05T11:47:09Z" finished-at="2014-03-05T11:47:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="FAIL" signature="toOutbox()[pri:0, instance:homework1.SmokeTest2@287cbe54]" name="toOutbox" duration-ms="16154" started-at="2014-03-05T11:47:27Z" finished-at="2014-03-05T11:47:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at homework1.SmokeTest2.toOutbox(SmokeTest2.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- toOutbox -->
        <test-method status="PASS" signature="end()[pri:0, instance:homework1.SmokeTest2@287cbe54]" name="end" is-config="true" duration-ms="740" started-at="2014-03-05T11:47:43Z" finished-at="2014-03-05T11:47:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- homework1.SmokeTest2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
